apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: expense-tracker

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - backend-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml

commonLabels:
  app.kubernetes.io/name: expense-tracker
  app.kubernetes.io/version: "1.0.0"
